# run tests in parallel
matrix:
  include:
    - language: node_js
      node_js: 6.14
      before_script:
        - cd search-portal-app
      script:
        - npm start

  - language: php
    php:
      - 5.4
      - 5.5
      - 5.6
    before_script:
      - cd elgg-plugin/solr_api


# configure notifications (email, IRC, campfire etc)
notifications:
  email: 
    - internalfire5@live.com

