language: node_js

node_js:

  # current version 6.14.1
  - 6.14


script: cd search-portal-app

# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "irc.freenode.org#yourfavouriteroomfortravis"

