language: node_js

node_js:

  # current version 6.14.1
  - 6.14


# start app, run process in background, wait, run test script
script: 
  - cd search-portal-app
  - npm run start & sleep 5; npm run test-pa11y;


# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "irc.freenode.org#yourfavouriteroomfortravis"

