# run tests in parallel
matrix:
  include:

    - language: node_js
      node_js:
        - stable
      script:
        - cd search-portal-app

    - language: php
      php:
        - 5.4
        - 5.5
        - 5.6
      script:
        - cd elgg-plugin/solr_api

    - language: generic
      sudo: required
      services: 
        - docker
      script:
        - cd docker-configuration-files
#     before_install:
#       - docker info
#     jobs:
#       include:
#         - stage: build, test, deploy
#           env:
#           - PROCESS=7.3/slim
#           script: tools/build_test_push.sh 7.3/slim

# configure notifications (email, IRC, campfire etc)
notifications:
  email: 
    recipients:
      - internalfire5@live.com

